#!/bin/sh

# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

set -eu

: "${ORACLE_SYS_PASSWORD:?ORACLE_SYS_PASSWORD is required}"
: "${ORACLE_RECEIVER_PASSWORD:?ORACLE_RECEIVER_PASSWORD is required}"

ORACLE_CONTAINER="${ORACLE_CONTAINER:-oracle-ee}"
ORACLE_PDB="${ORACLE_PDB:-ORCLPDB1}"
ORACLE_BENCHMARK_ROWS="${ORACLE_BENCHMARK_ROWS:-10000000}"
ORACLE_COLLISION_SIZE="${ORACLE_COLLISION_SIZE:-100}"

case "$ORACLE_BENCHMARK_ROWS" in
  *[!0-9]* | 0) echo "ORACLE_BENCHMARK_ROWS must be a positive integer" >&2; exit 1 ;;
esac
case "$ORACLE_COLLISION_SIZE" in
  *[!0-9]* | 0) echo "ORACLE_COLLISION_SIZE must be a positive integer" >&2; exit 1 ;;
esac
if ! printf '%s' "$ORACLE_RECEIVER_PASSWORD" |
  grep -Eq '^[A-Za-z0-9_#$!@%+=.-]{12,64}$'; then
  echo "ORACLE_RECEIVER_PASSWORD contains unsupported characters or is not 12-64 characters" >&2
  exit 1
fi
if ! printf '%s' "$ORACLE_SYS_PASSWORD" |
  grep -Eq '^[A-Za-z0-9_#$!@%+=.-]{12,64}$'; then
  echo "ORACLE_SYS_PASSWORD contains unsupported characters or is not 12-64 characters" >&2
  exit 1
fi

docker exec -i "$ORACLE_CONTAINER" sqlplus -L -s /nolog <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
CONNECT SYSTEM/"${ORACLE_SYS_PASSWORD}"@//localhost:1521/${ORACLE_PDB}
SET ECHO ON
SET TIMING ON

BEGIN
  EXECUTE IMMEDIATE 'DROP USER OTAP_RECEIVER CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP USER OTAP_BENCH CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

CREATE USER OTAP_BENCH IDENTIFIED BY "${ORACLE_RECEIVER_PASSWORD}"
  DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER OTAP_RECEIVER IDENTIFIED BY "${ORACLE_RECEIVER_PASSWORD}";
GRANT CREATE SESSION TO OTAP_RECEIVER;

CREATE TABLE OTAP_BENCH.OTAP_ORACLE_EVENTS (
  EVENT_TS TIMESTAMP(9) NOT NULL,
  EVENT_ID NUMBER(19) NOT NULL,
  PAYLOAD VARCHAR2(200) NOT NULL,
  CONSTRAINT OTAP_ORACLE_EVENTS_PK PRIMARY KEY (EVENT_ID)
) NOLOGGING;

INSERT /*+ APPEND */ INTO OTAP_BENCH.OTAP_ORACLE_EVENTS (
  EVENT_TS,
  EVENT_ID,
  PAYLOAD
)
WITH generated_rows AS (
  SELECT
    ((chunks.chunk_id - 1) * 10000) + offsets.row_offset AS event_id
  FROM (
    SELECT LEVEL AS chunk_id
    FROM DUAL
    CONNECT BY LEVEL <= CEIL(${ORACLE_BENCHMARK_ROWS} / 10000)
  ) chunks
  CROSS JOIN (
    SELECT LEVEL AS row_offset
    FROM DUAL
    CONNECT BY LEVEL <= 10000
  ) offsets
)
SELECT
  TIMESTAMP '2026-01-01 00:00:00'
    + NUMTODSINTERVAL(
        FLOOR((event_id - 1) / ${ORACLE_COLLISION_SIZE}),
        'SECOND'
      ),
  event_id,
  RPAD('event-' || TO_CHAR(event_id, 'FM000000000000'), 200, 'x')
FROM generated_rows
WHERE event_id <= ${ORACLE_BENCHMARK_ROWS};
COMMIT;

CREATE INDEX OTAP_BENCH.OTAP_ORACLE_EVENTS_CURSOR_IDX
  ON OTAP_BENCH.OTAP_ORACLE_EVENTS (EVENT_TS, EVENT_ID)
  NOLOGGING;
GRANT SELECT ON OTAP_BENCH.OTAP_ORACLE_EVENTS TO OTAP_RECEIVER;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(
    ownname => 'OTAP_BENCH',
    tabname => 'OTAP_ORACLE_EVENTS',
    cascade => TRUE
  );
END;
/

SELECT COUNT(*) AS BENCHMARK_ROWS
FROM OTAP_BENCH.OTAP_ORACLE_EVENTS;
EXIT
SQL

printf '\nPrepared %s indexed Oracle rows for the OTAP_RECEIVER principal.\n' \
  "$ORACLE_BENCHMARK_ROWS"
